eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.10.0.14:8761/eureka/
  instance:
    hostname: 10.10.0.14

microservice:
  feedback-service:
    endpoints:
      endpoint:
        uri: http://FEEDBACK-SERVICE/feedback/**    
