eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

microservice:
  feedback-service:
    endpoints:
      endpoint:
        uri: http://FEEDBACK-SERVICE/feedback/**    
